### ISSUE TITLE
allow individuell oauth2 config 

### ISSUE THREAD

**Issue by NiasSt90** [benbucksch/autoconfig-spec#1]
In your xml format description [here](https://www.bucksch.org/1/projects/thunderbird/autoconfiguration/config-file-format.html) there was an `oauth2` block to configure a individuell oauth2/oidc configuration.
But these configuration sections lacks  the option to provide a `clientId`/`clientSecret` like in the following example.

```xml
<incomingServer type="imap">
      <hostname>imap.my-server.com</hostname>
      <port>993</port>
      <socketType>SSL</socketType>
      <username>%EMAILADDRESS%</username>
      <authentication>OAuth2</authentication>
      <authentication>password-cleartext</authentication>
      <oAuth2>
        <issuer>sso.my-keycloak.com/auth/realms/myRealm<issuer>
        <scope>imap<scope>
        <authURL>https://sso.my-keycloak.com/auth/realms/myRealm/protocol/openid-connect/auth</authURL>
        <tokenURL>https://sso.my-keycloak.com/auth/realms/myRealm/protocol/openid-connect/token</tokenURL>
        <clientId>MUA</clientId>
        <clientSecret>not-so-secret</clientSecret>
      <oAuth2>
    </incomingServer>
```

In my opinion is this easier than to try to create dynamically a client on the target IDP. 
(mentioned [here](https://bugzilla.mozilla.org/show_bug.cgi?id=1602166))

**Comment by benbucksch** [comment]
I agree. There's already `<clientID>`, and I just added `<clientSecret>`.

FIXED
