### ISSUE TITLE
XML syntax typos in sample XML

### ISSUE THREAD

**Issue by gabviv73** [benbucksch/autoconfig-spec#10]
On line 128, the tag is not closed

Wrong:

      <serverURL>https://jmap.example.com/remote.php/dav<serverURL>

Right:

      <serverURL>https://jmap.example.com/remote.php/dav</serverURL>

**Comment by benbucksch** [comment]
Thanks! Any other mistakes that I can fix at the same time?

**Comment by gabviv73** [comment]
Nope to my eyes and to Firefox...
I've used your template to build this: [https://github.com/gabviv73/EmailAutoConfig](https://github.com/gabviv73/EmailAutoConfig). Tested with Thunderbird and it works. Unfortunately, Caldav and Carddav seems to not be implemented in TB autoconfig: am I right ?

**Comment by benbucksch** [comment]
> Unfortunately, Caldav and Carddav seems to not be implemented in TB autoconfig: am I right ?

Correct. Thunderbird uses RFC 6764.

**Comment by benbucksch** [comment]
FIXED
@gabviv73 Thanks for the report.
