### ISSUE TITLE
Consider HTTP downgrade attacks

### ISSUE THREAD

**Issue by mimi89999** [benbucksch/autoconfig-spec#12]
In the security considerations only an attack on the DNS protocol was considered and DoH was presented as a possible mitigation.

Even with DNS secured by using DoH, I think it might still be possible for an attacker performing a MITM attack to present a forged configuration.

An attacker could monitor HTTPS connections and drop them if the value of the SNI header starts with `autoconfig.`. The client could then fallback to the HTTP URL from 1.3 and the attacker could present it with the forged configuration.

**Comment by mimi89999** [comment]
@benbucksch I saw that the draft was adopted. Could you please give a comment on that issue?

**Comment by mimi89999** [comment]
> The attacker would need to sit between the user and the server. This requires physical access or national level access. While such scenarios exist, this prevents by far most attackers.

Targeted attacks are indeed difficult, but opportunistic ones are not. Think about an attacker with an access point in an airport/cafe/restaurant/university/library/whatever. He could gather credentials and then use them to extract sensitive data from the inbox or attempt to reset passwords to sensitive online accounts as most send password reset links via e-mail without requiring any additional authentication.

> It requires an active attack, not just a passive attack. This presents a hurdle for attackers that operate on the national level, because it exposes them. Same is true for attackers with physical access who want to stay undetected. There are nations who do not care, and are well-known to hack their citizens, but then their citiens can be more careful, see below.

"You say there is an issue with our Wi-Fi? But it works fine for me. I can access google.com and bbc.com just file. See? Since you really insist, I will ask the IT guy about this. He comes here once a week." That's assuming that there is somebody who noticed the attack and had enough technical knowledge to understand what was going on.

> In 15 years since this protocol is deployed in the wild, I have never heard of such an attack.

Before HTTPS was common, warnings against using public Wi-Fi networks were common.

> The attacker would need to time the attack in the exact moment when the user configures his email address.

Even if the attack would yield only one pair of credentials after several days, if the inbox contains very sensitive data or the user has sensitive online accounts linked to that e-mail address, it could still make the attack worthy.

> Most importantly, the user has to explicitly verify the configuration. This is a mandatory part of the protocol, exactly because we cannot be 100% certain and bullet proof, at least not in theory.

That's very convenient to put in the spec, but that's basically assuming that the user understands the screen with the configuration and any potentially displayed warnings and not just click through it. That's also assuming that the user knows the correct config or knows how to find it. That's quite unlikely.

**Comment by benbucksch** [comment]
> Think about an attacker with an access point in an airport/cafe/restaurant/university/library/whatever. 

You wouldn't normally configure a new mail account in such situations.

The mitigations work in concert together. You can shoot holes in every single one of them, but **in combination**, the likeliness of a successful attack is very low.

It's nice to be 100% secure, but if that's not possible, or it means that we get no config at all in many cases, then that's not helpful.

The only working solution I can imagine is to move ISP HTTP (step 1.3) below the ISP DB (step 2.1) in priority, and possibly below MX (step 3.x), if you use DoH.

**Comment by mimi89999** [comment]
If this is considered an acceptable risk, maybe it's worth at least mentioning it in security considerations? That section currently only mentions risks related to the SRV protocol, but not HTTP.

**Comment by benbucksch** [comment]
Fair point, yes.

**Comment by benbucksch** [comment]
It's mentioned in section 9.2 "DNS", with the first sentence: "Any protocol that relies on DNS without further validation, e.g. http, should be considered insecure." However, the title says only "DNS", and the rest of the section speaks only about DNS.

Also, I should maybe explictly explain the above concept of mitigation by a combination of mitigation factors.
