### ISSUE TITLE
https://autoconfig.ispdb.net/v1.1/ does not exist

### ISSUE THREAD

**Issue by link2xt** [benbucksch/autoconfig-spec#5]
Since commit
https://github.com/benbucksch/autoconfig-spec/commit/702fc975c969432ce5ed14354c5e75bf1f1ad936
there is a sentence
"A public mail config database is available at base URL `https://autoconfig.ispdb.net/v1.1/`."

It should either be removed or reverted to https://autoconfig.thunderbird.net/v1.1/, which is the standard ISPDB used by Thunderbird, K-9 and Delta Chat.

I think it is fine to keep Thunderbird URL here.

**Comment by benbucksch** [comment]
It will exist.

**Comment by benbucksch** [comment]
I've changed the base URL to https://v1.ispdb.net/

Need to wait for DNS to update for it to go live.
