### ISSUE TITLE
mAuth specification

### ISSUE THREAD

**Issue by link2xt** [benbucksch/autoconfig-spec#6]
Specification refers to mAuth (OAuth for email), but there is no link to mAuth. Is there an existing specification for it?

**Comment by benbucksch** [comment]
It is in the works.

**Comment by benbucksch** [comment]
Here you are :)
* https://benbucksch.github.io/mauth-spec/draft-mauth.html
* https://github.com/benbucksch/mauth-spec
* https://datatracker.ietf.org/doc/draft-bucksch-mauth/

FIXED
